tests = [ {'description': 'PINA: 0x00 => PORTB: 0x00',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTB',0x00)],
    },
    {'description': 'PINA: 0x01 => PORTB: 0x01.',
    'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 5} ], # Set PIN to val then run one iteration
       # {'inputs': [('PIN',<val>)], 'time': 300 }, # Set PIN to val then run 300 ms
       # {'inputs': [('PIN',<val>)], 'iterations': 1, 'expected': [('PORT',<val>)]},
       # 'inputs': [('PIN',<val>)], 'time': 600}, ],
    'expected': [('PORTB',0x01)],
    },
     {'description': 'PINA: 0x02 => PORTB: 0x00',
    'steps': [ {'inputs': [('PINA',0x02)], 'iterations': 5 } ],
    'expected': [('PORTB',0x00)],
    },
    {'description': 'PINA: 0x03 => PORTB: 0x00',
    'steps': [ {'inputs': [('PINA',0x03)], 'iterations': 5 } ],
    'expected': [('PORTB',0x00)],
    },
    ]
